version: '3.7'

volumes:
  sql-data-1:
    name: sql-data-1
    #external: true
  app-data-1:
    name: app-data-1

services:
  #kronessqldb:
  #  container_name: kronessqldb
  #  restart: always
  #  user: root
  #  ports:
  #    - "1433:1433"
  #  volumes:
  #    - sql-data-1:/var/opt/mssql/data
  #    - sql-data-1:/var/opt/mssql/log
  #  environment: 
  #   ACCEPT_EULA: "Y"
  #   MSSQL_SA_Password: "Testbar123"
  iam.identity:
    container_name: iam.identity
    user: root
    hostname: iam.identity
    restart: on-failure
        #ipv4_address: 172:16.238.4
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=443
      #- ASPNETCORE_Kestrel__Certificates__Default__Password="eEtNrrgzIApOTWglaySv"
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ssl-iam-identity-docker.pfx -v %USERPROFILE%\certificate:/https/
      - "ConnectionStrings:DBConnection=Server=kronessqldb;Database=ID4db;User ID=sa;"
      - ASPNETCORE_URLS=https://+;http://+
    #depends_on:
      #- kronessqldb
      #- reverseproxy
    ports:
      - "8001:80"
      - "5005:443"
    volumes:
      - app-data-1:/app/logs